name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [1, 2, 3, 4, 5, 6, 7]

    steps:
    - uses: actions/checkout@v3
    - name: Repeater compile
      run: g++ -O3 intention_repeater_max_5.2.cpp
    - name: Repeater run
      run: ./a.out --dur 06:00:00 --imem 6 --intent "INTENTIONS.ZIP THANK YOU SO MUCH"
