name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        Plan: [1, 2, 3, 4, 5]

    steps:
    - uses: actions/checkout@v3
    - name: Repeater compile
      run: g++ -O3 intention_repeater_max_5.2.cpp
    - name: Repeater run
      run: ./a.out --dur 05:58:00 --imem 13.5 --intent "INTENTIONS.ZIP THANKS"
